### ISSUE TITLE
do not print all combinations

### ISSUE THREAD

**Issue by iorixxx** [AnadoluUniversityCeng/bim313-hw1-whiskermrr#1]
It looks like your program prints all of the 85320 combinations, whats why this gets zero at the moment. Please fix the code as soon as possible. Print cities/triangles that violate the triangle inequality.

**Comment by whiskermrr** [comment]
Yes, it prints all of them because i wanted it to. People are copy-pasting
so i decided to made a mistake. I will correct my application right now.

2016-11-10 12:14 GMT+02:00 Ahmet Arslan <notifications@github.com>:
